language: objective-c
osx_image: xcode10.2
group: "stable"
dist: "osx"
os: "osx"
env:
  global:
    - DESTINATION="arch=x86_64"
    - XCODE_SCHEME="PactMacOSExample"
    - XCODE_PROJECT="PactMacOSExample.xcodeproj"
before_install:
  - brew tap pact-foundation/pact-ruby-standalone
  - brew install pact-ruby-standalone
before_script:
  - carthage update --platform macOS --no-use-binaries
  - mkdir -p "./tmp"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project $XCODE_PROJECT -scheme $XCODE_SCHEME -destination $DESTINATION -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO test -enableCodeCoverage YES | xcpretty -c;
