name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:

env:
  DESTINATION: "arch=x86_64"
  XCODE_SCHEME: "PactMacOSExample"
  XCODE_PROJECT: "PactMacOSExample.xcodeproj"

jobs:
  test_macOS:
    name: Test macOS project
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: Carthage/build
          key: ${{ runner.os }}-pactmacOsExample-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-pactmacOsExample-
            ${{ runner.os }}-

      - name: Prepare tools
        run: |
          brew tap pact-foundation/pact-ruby-standalone
          brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
          brew install pact-ruby-standalone xcbeautify

      - name: Run tests
        run: |
          scripts/carthage_xcode12 update --platform macos --no-use-binaries
          mkdir -p "./tmp"
          xcodebuild -project $XCODE_PROJECT -scheme $XCODE_SCHEME -destination $DESTINATION -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES CODE_SIGNING_REQUIRED=NO test -enableCodeCoverage YES | xcbeautify

